CLASS_NAMES = [
    "Apple",
    "Banana",
    "Beetroot",
    "Bell Pepper",
    "Cabbage",
    "Capsicum",
    "Carrot",
    "Cauliflower",
    "Chilli Pepper",
    "Corn",
    "Cucumber",
    "Eggplant",
    "Garlic",
    "Ginger",
    "Grapes",
    "Jalepeno",
    "Kiwi",
    "Lemon",
    "Lettuce",
    "Mango",
    "Onion",
    "Orange",
    "Paprika",
    "Pear",
    "Peas",
    "Pineapple",
    "Pomegranate",
    "Potato",
    "Raddish",
    "Soy Beans",
    "Spinach",
    "Sweetcorn",
    "Sweet Potato",
    "Tomato",
    "Turnip",
    "Watermelon"
]
